# version: '3.8'

# services:
#   web:
#     image: app-name:latest
#     build:
#       target: web
#       context: .
#     env_file:
#       - .env
#     ports:
#       - "8000:80"
#     volumes:
#       - .:/var/www/html
#     depends_on:
#       - db
#     command: >
#       sh -c "php artisan migrate:refresh --seed"

#   db:
#     platform: "linux/amd64"
#     image: mysql:5.7
#     env_file:
#       - .env.docker
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: laravel
#       MYSQL_USER: laraveluser
#       MYSQL_PASSWORD: laravelpass
#     ports:
#       - "3306:3306"
#     volumes:
#       - dbdata:/var/lib/mysql

# volumes:
#   dbdata:
